# Number of layers don't matter in bulder
# Currently only supports amd64,arm64/v8, ppc64le, s390x
ARG NODE_VERSION=16.20.2
FROM node:${NODE_VERSION}-alpine AS builder

# Add the latest alpine repositories
RUN echo "http://dl-3.alpinelinux.org/alpine/latest-stable/main" > /etc/apk/repositories \
  && echo "http://dl-3.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories \
  && apk update && apk upgrade --available --no-cache

# Setup the build environment
RUN  apk update && apk upgrade \
  && apk add --no-cache --update --upgrade --virtual .build-deps-full \
    coreutils \
    bind-tools \
    git \
    unzip \
    wget \
    curl \
    bash \
    gcompat \
    openjdk11-jdk \
  && rm -rf /var/cache/apk/*

WORKDIR /signum-node

COPY . .

#RUN node -v
#RUN npm -v

# Not needed as is contained in the base image
RUN sed -i 's/download = true/download = false/g' /signum-node/build.gradle

# Run gradle tasks
RUN chmod +x /signum-node/gradlew \
  && /signum-node/gradlew clean dist jdeps \ 
    -Pjdeps.recursive=true \
    -Pjdeps.ignore.missing.deps=true \
    -Pjdeps.print.module.deps=true

# Unzip the distribution into /signum and cd into it
RUN unzip -o build/distributions/signum-node.zip -d /signum
WORKDIR /signum

# Clean up /signum
RUN rm -rf /signum/signum-node.exe 2> /dev/null || true \
  && rm -rf /signum/signum-node.zip 2> /dev/null || true \
  && rm -rf /signum/*.sh 2> /dev/null || true

# create required directories
RUN mkdir -p /requirements/sbin \
  && mkdir -p /requirements/etc \
  && mkdir -p /signum/db

ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk"

# Create a custom JRE 
RUN ${JAVA_HOME}/bin/jlink \
  --module-path ${JAVA_HOME}/jmods:/signum/signum-node.jar \
  --add-modules $(cat /signum-node/build/reports/jdeps/print-module-deps-main.txt) \
  --strip-debug \
  --no-man-pages \
  --no-header-files \
  --compress=2 \
  --output /requirements/jre

# Copy required libraries for Java
RUN ldd /requirements/jre/bin/java | awk 'NF == 4 { system("cp --parents " $3 " /requirements") }'

# Create user/group and set permissions including nologin
RUN cp /sbin/nologin /requirements/sbin/nologin \
  && echo "signum:x:989:989:Signum-Node User:/conf:/sbin/nologin" > /requirements/etc/passwd

## Final Image Notes
# - Image is based on scratch to keep the size as small as possible
# - Scratch is basically empty so we need to copy in the required libraries and signum-node to the / (root)
# - Since /signum is copied to root and contains dirs db & conf symlink is no longer needed and will
#   function the same as the non-slim image having the same volume mounts of /db & /conf
# - dir /tmp is used for java logging lock file (compatibility for podman)
FROM scratch
LABEL maintainer="GittRekt"

COPY --from=builder /requirements /
COPY --from=builder --chown=989:989 /signum /

VOLUME ["/conf", "/db", "/tmp"]
EXPOSE 8125/tcp 8123/tcp
USER 989:989
ENTRYPOINT [ "/jre/bin/java", "-XX:MaxRAMPercentage=90.0", "-jar", "/signum-node.jar", "--headless", "--update-wallets", "-c", "/conf/" ]