name: Docker Image CI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-latest:
    environment: dockerhub
    name: Build latest image
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY_USERNAME }}/${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build push and image
        uses: docker/build-push-action@v5
        with:
          file: 'Dockerfile'
          context: .
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.REGISTRY_USERNAME }}/${{ github.repository }}:latest
          cache-to: type=inline
          push: true
          labels: ${{ steps.meta.outputs.labels }}
